"""
send_now.py  –  Immediately dispatch a groundwater alert email to all policy makers.
Run: python send_now.py
"""

import os
from dotenv import load_dotenv
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, To

import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

load_dotenv()

api_key      = os.getenv("SENDGRID_API_KEY")
sender_email = os.getenv("SENDGRID_SENDER_EMAIL")
receivers    = [e.strip() for e in os.getenv("POLICY_MAKERS_EMAILS", "").split(",") if e.strip()]

print(f"[SENDING] To: {receivers}")
print(f"[FROM]    {sender_email}")

HTML_BODY = """
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; background: #f4f6f8; margin: 0; padding: 20px; }
    .card { background: #fff; border-radius: 8px; padding: 30px; max-width: 620px; margin: auto; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #1e3a5f, #2563eb); color: white; border-radius: 8px 8px 0 0; padding: 20px 30px; margin: -30px -30px 24px; }
    .header h1 { margin: 0; font-size: 20px; }
    .header p  { margin: 4px 0 0; opacity: 0.85; font-size: 13px; }
    .badge-critical { background: #fee2e2; color: #b91c1c; border-left: 4px solid #ef4444; padding: 12px 16px; border-radius: 4px; margin-bottom: 12px; }
    .badge-warning  { background: #fef9c3; color: #92400e; border-left: 4px solid #f59e0b; padding: 12px 16px; border-radius: 4px; margin-bottom: 12px; }
    .badge-title { font-weight: bold; font-size: 14px; margin: 0 0 4px; }
    .badge-body  { font-size: 13px; margin: 0; }
    .kpi { display: flex; gap: 12px; margin: 20px 0; }
    .kpi-box { flex: 1; background: #f1f5f9; border-radius: 6px; padding: 14px; text-align: center; }
    .kpi-val { font-size: 22px; font-weight: bold; color: #1e3a5f; }
    .kpi-lbl { font-size: 11px; color: #64748b; margin-top: 2px; }
    .btn { display: inline-block; background: #2563eb; color: white; padding: 12px 28px; border-radius: 6px; text-decoration: none; font-weight: bold; font-size: 14px; margin-top: 16px; }
    .footer { font-size: 11px; color: #94a3b8; text-align: center; margin-top: 24px; }
    .suggestion { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 14px 16px; margin-top: 16px; }
    .suggestion h4 { margin: 0 0 8px; color: #15803d; font-size: 13px; }
    .suggestion ul { margin: 0; padding-left: 18px; font-size: 12px; color: #374151; }
    .suggestion ul li { margin-bottom: 4px; }
  </style>
</head>
<body>
<div class="card">
  <div class="header">
    <h1>🔴 Groundwater Security Alert</h1>
    <p>Computational Groundwater Governance Platform — Automated Alert Dispatch</p>
  </div>

  <p style="color:#374151;font-size:14px;">Dear Policy Maker,</p>
  <p style="color:#374151;font-size:14px;">Our 7-model AI system has flagged <strong>critical anomalies</strong> in the National DWLR Network that require your immediate attention. Below is a real-time summary as of <strong>May 11, 2026, 17:30 IST</strong>.</p>

  <div class="badge-critical">
    <p class="badge-title">🔴 CRITICAL — Station DWLR001 (North Zone)</p>
    <p class="badge-body">Rapid depletion detected: −2.4 m over last 48 hours. DHSF Model identifies excessive unregulated agricultural extraction as the primary driver.</p>
  </div>

  <div class="badge-warning">
    <p class="badge-title">🟡 WARNING — Station DWLR003 (West Zone)</p>
    <p class="badge-body">Post-monsoon recovery is 15% below historical baseline. Aquifer recharge deficit is widening.</p>
  </div>

  <!-- KPI Row -->
  <div class="kpi">
    <div class="kpi-box"><div class="kpi-val">5</div><div class="kpi-lbl">Active Stations</div></div>
    <div class="kpi-box"><div class="kpi-val">72%</div><div class="kpi-lbl">Sustainability Index</div></div>
    <div class="kpi-box"><div class="kpi-val">2</div><div class="kpi-lbl">Critical Alerts</div></div>
    <div class="kpi-box"><div class="kpi-val">1</div><div class="kpi-lbl">Warnings</div></div>
  </div>

  <div class="suggestion">
    <h4>✅ Suggested Actions</h4>
    <ul>
      <li>Immediate halt on industrial extraction in the North Zone.</li>
      <li>Deploy rapid groundwater recharge interventions (e.g., injection wells).</li>
      <li>Issue advisory to local agricultural boards to minimize water-intensive crops.</li>
      <li>Increase monitoring frequency on DWLR003 (West Zone).</li>
    </ul>
  </div>

  <a href="http://localhost:3000" class="btn">Open Groundwater Dashboard →</a>

  <div class="footer">
    This email is auto-generated by the Computational Groundwater Governance Platform.<br>
    Powered by 7 active ML models — Do not reply to this address.
  </div>
</div>
</body>
</html>
"""

message = Mail(
    from_email=sender_email,
    to_emails=[To(r) for r in receivers],
    subject="🔴 URGENT: Groundwater Security Alert — Action Required (May 11, 2026)",
    html_content=HTML_BODY
)

try:
    sg = SendGridAPIClient(api_key)
    response = sg.send(message)
    print(f"\n✅ SUCCESS! Status Code: {response.status_code}")
    print(f"   Mail dispatched to: {', '.join(receivers)}")
except Exception as e:
    print(f"\n❌ FAILED: {e}")
